name: CI/CD Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: front
      REGISTRY: ${{ secrets.REGISTRY_URL }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Kakao Cloud Registry
        run: |
          echo "${{ secrets.KCR_PASSWORD }}" | docker login kc-sfacspace.kr-central-2.kcr.dev -u "${{ secrets.KCR_USER }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          docker tag $REGISTRY/$IMAGE_NAME:$IMAGE_TAG $REGISTRY/$IMAGE_NAME:latest
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Checkout test Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          path: test

      - name: Update values.yaml
        run: |
          sed -i "s|tag:.*|tag: \"${IMAGE_TAG}\"|" test/helm-chart/front-chart/values.yaml

      - name: Commit & Push changes
        run: |
          cd test
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm-chart/front-chart/values.yaml
          git commit -m "Update frontend image tag to ${IMAGE_TAG}"
          git push origin main
